<?php
header("Content-Type: text/html; charset=utf-8");


/**
 * Implements hook_menu()
 */
function mod_menu(){
    $items = array();
    $items['mypage-one'] = array(
        'title'                 =>'my module',
        'page callback'         => 'my_function',
        'access callback'       => TRUE
    );
    return $items;
}

function my_function(){

    $ch = curl_init();

    // 2. указываем параметры, включая url
    curl_setopt($ch, CURLOPT_URL, "http://www.cbr.ru/scripts/XML_daily.asp");
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HEADER, 0);

    // 3. получаем HTML в качестве результата
    $output = curl_exec($ch);
    // 4. закрываем соединение
    curl_close($ch);
    $i=0;
    $kurs= simplexml_load_string($output);
    //// указываем язык
    $node = array(
        // Заголовок ноды
        'title' => 'новый',
        // Тип материала, к которому относится нода
        'type' => 'Сurrency',
        'uid' => 1,
    );
    $object= node_load(10);
    echo $object->title;
    /*foreach ($kurs->Valute as $Valute){

    }*/
    #dsm($kurs);
}

?>