<?php
//session_start();
error_reporting(E_ALL);
ini_set('display_errors', 1);
/**
 * Implements hook_menu
 */

function my_module_menu(){
    $items = array();
    $items['page'] = array(
        'title'                 => 'CURRENCY',
        'page callback'         => 'drupal_get_form',
        'page arguments'        =>  array('page_form'),
        'access callback'       => TRUE
    );
    return $items;
}
/**
 * Implements my_first
 */
function page_form($form, $form_state) {
    $form = array();
    $form['number1'] = array(
        '#type' => 'textfield',
        '#title' => t('Number 1'),
        '#size' => 20,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('GO!'),
    );
    return $form;
}
function page_form_submit($form, &$form_state) {
    $num1 = $form_state['values']['number1'];
   $_SESSION['data']=$num1;
    $num2=date("Y-m-d");
    drupal_set_message(strtotime($num1));
    drupal_set_message(strtotime($num2));

    drupal_set_message(date("d-m-Y H:i:s",strtotime($num1)));
    drupal_set_message(date("d-m-Y H:i:s",strtotime($num2)));
    //drupal_set_message($_SESSION['data']);
   // return mod_table_menu();
    mod_table_menu();
}
function my_first($num1){
   $header = array(
        array('data' => t('№')),
        array('data' => t('Сurrency')),
        array('data' => t('The course at the moment'))
    );


    $i=0;
    $nids = db_select('node', 'n')
        ->fields('n', array('nid'))
        ->condition('n.type', '_urrency')
        ->execute()
        ->fetchCol();
    print_r($nids);
    echo 'lylly';
    if($nids==null){
        echo 'pisda';
    } else{
        foreach ($nids as $Valute){
            $node=node_load($nids[$i]);
            $str=$node->field_time2[LANGUAGE_NONE][0]['value'];
            $n=strpos($str,$num1);
          //  drupal_set_message($num1,$str);
            if($num1==$str) {
                $i=$i+1;
                $name =  $node->field__currency_name[LANGUAGE_NONE][0]['value'];
                $val = $node->field_value[LANGUAGE_NONE][0]['value'];
                $rows[] = array(array('data' => $i),array('data' => $name),
                    array('data' => $val),
                );
            }
        }
    }
    #dsm($kurs);
  //  drupal_set_message(theme('table', array('header' => $header, 'rows'=> $rows)));


}


?>