<?php
error_reporting(E_ALL);

ini_set('display_errors', 1);
/**
 * Implements hook_menu
 */

function my_module_menu(){
    $items = array();
    $items['page'] = array(
        'title'                 => 'CURRENCY',
        'page callback'         => 'my_first',
        'access callback'       => TRUE
    );
    return $items;
}
/**
 * Implements my_first
 */

function my_first(){
    $header = array(
        array('data' => t('Сurrency')),
        array('data' => t('The course at the moment'))
    );
    $ch = curl_init();
	drupal_set_message(t(’Вы находитесь на ветке тест’));
// 2. указываем параметры, включая url  
    curl_setopt($ch, CURLOPT_URL, "http://www.cbr.ru/scripts/XML_daily.asp");
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HEADER, 0);

// 3. получаем HTML в качестве результата  
    $output = curl_exec($ch);

// 4. закрываем соединение  
    curl_close($ch);
    $kurs= simplexml_load_string($output);
    if($kurs==null){
        echo 'pisda';
    } else{
        foreach ($kurs->Valute as $Valute){
            $name=$Valute->Name;
            $val=$Valute->Value;
            $rows[] = array(array('data' => $name),
                array('data' => $val),
            );
        }
    }
    dsm($kurs);
    return theme('table', array('header' => $header, 'rows'=> $rows));

}


?>